#!/bin/bash
TRTLLM_VERSION=$(trtllm-serve --help 2>&1 | awk '/TensorRT-LLM version:/ {print $4}')
python /app/tensorrt_llm/benchmarks/cpp/prepare_dataset.py \
	--stdout \
	--tokenizer /model_weights/$MODEL \
	token-norm-dist \
	--input-mean 128 \
	--output-mean 128 \
	--input-stdev 0 \
	--output-stdev 0 \
	--num-requests 3000 > /tmp/synthetic_128_128.txt

trtllm-bench --model /model_weights/$MODEL/ \
	--model_path /model_weights/$MODEL/ \
	throughput \
	--dataset /tmp/synthetic_128_128.txt \
	--backend pytorch \
	--extra_llm_api_options /extra_llm_api_options/pytorch-small-batch.yml \
	2>&1 | tee /benchmarks/"$MODEL-$TRTLLM_VERSION-pytorch-bench-$(date +%m-%d-%Y-%H-%M-%S).txt"
