#!/bin/bash
python /app/tensorrt_llm/benchmarks/cpp/prepare_dataset.py --stdout \
	--tokenizer /model_weights/$MODEL \
	token-norm-dist \
	--input-mean 128 \
	--output-mean 128 \
	--input-stdev 0 \
	--output-stdev 0 \
	--num-requests 3000 > /tmp/synthetic_128_128.txt

trtllm-bench --model /model_weights/$MODEL build \
	--quantization FP8 \
	--dataset /tmp/synthetic_128_128.txt

trtllm-bench --model /model_weights/$MODEL \
	throughput \
	--dataset /tmp/synthetic_128_128.txt \
	--engine_dir /model_weights/$MODEL/tp_1_pp_1 \
	2>&1 | tee "$MODEL-enginge-bench-$(date +%m-%d-%Y-%H-%M-%S).txt"
